### ISSUE TITLE
Errors when building Linux.

### ISSUE THREAD

**Issue by says112** [TribeCrypto/tribe#7]
Errors when building Linux.
![Снимок экрана (103)](https://github.com/TribeCrypto/tribe/assets/22127398/116dc709-5f9d-441f-b449-27b0560b4456)

**Comment by tribetrb** [comment]
You are running a newer version of Ubuntu, the error you see is because Tribe uses openssl version 1.0.2 in Ubuntu 16.0.4. Newer Ubuntu are using 1.1.1. Check with "openssl version".
